config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"

  # BACK-END
  resources :contents
  resources :teams
  resources :players do
    collection do 
      get :import
      get :import_numbers
      get :calculate_prices
    end
  end
  resources :games do
    collection do 
      get :import
      get :import_table
    end
  end
  resources :statistics do
    collection do 
      get :import
    end
  end
  resources :settings

  # API #
  namespace :api do
    namespace :v1 do 
      resources :contents
      resources :games do 
        collection do
          get :calendar
        end
      end
      resources :players
      resources :statistics do
        collection do
          get :trending_players
        end
      end
      resources :teams
    end
  end

end

app/models/statistic.rb
# == Schema Information
#
# Table name: statistics
#
#

class Statistic < ActiveRecord::Base
  
  FIELDS = %w( game min pt t2 t3 t1 reb a br bp c tap m fp fr mas_menos v sm )  
  FIELDS_DEFAULT = ["-", "0'", "0", "0/0", "0/0", "0/0", "0(0+0)", "0", "0", "0", "0", "0+0", "0", "0", "0", "0", "0", "0.00" ]  

  NUM_GAMES = Setting.find_by_key("session_rounds").value.to_i

  # !**************************************************
  # !                Associations
  # !**************************************************
  belongs_to :player

  # !**************************************************
  # !                Validations
  # !**************************************************

  # !**************************************************
  # !                Callbacks
  # !**************************************************
  #before_save :set_defaults

  # !**************************************************
  # !                  Other
  # !**************************************************  
  include StatisticAllowed
  scope :by_season, -> (season) { where(:season => season).first }
  scope :by_round,  -> (round)  { where(:round  => round).first }
  
  def to_s
    season + " - " + player.to_s
  end

  def self.num_games
    NUM_GAMES.to_i
  end

  def self.fields
    FIELDS
  end

  # !**************************************************
  # !                Imports
  # !**************************************************
  def self.import_statistics
    players_url = Setting.find_by_key("statistics_url").value
    players_html = Nokogiri::HTML(open(players_url.to_s))

    players_html.css("table.listaJugadores > tr").each do |player_row|
      name = player_row.css('td[1]//text()').to_s
      team_name = player_row.css('td[2]/text()').to_s

      unless name.blank?
        if player = Player.find_by_name(name)
          player.href = Array.wrap(player_row.css("td[1]/a").map { |link| link['href'] })[0].to_s
          import_statistic player
        end
      end
    end
  end

  def self.import_statistic player
    players_url = player.href
    players_url.force_encoding('binary')
    players_url = WEBrick::HTTPUtils.escape(players_url)
    player_html = Nokogiri::HTML(open(players_url))

    current_season = CURRENT_SEASON

    unless statistic = Statistic.where(season: current_season).where(player_id: player.id).first
      statistic = Statistic.new
      statistic.season = current_season
      statistic.player_id = player.id
      statistic.save!
    end

    session_rounds = Setting.find_by_key("session_rounds").value

    statistic.played_games = 0
    player_html.css("table.fichaJugadorStats > tr").each do |row_statistic|
      partido = row_statistic.css("th[1]/text()").to_s.downcase
      if partido == 'promedio' || partido == 'total' || (1..session_rounds.to_i).include?(partido.to_i)
        if (1..session_rounds.to_i).include?(partido.to_i)
          partido = "week_"+partido 
          plus = 0
        else
          plus = 1
        end
        game = row_statistic.css("td["+(2-plus).to_s+"]/text()")
        minutos = row_statistic.css("td["+(3-plus).to_s+"]/text()")
        puntos = row_statistic.css("td["+(4-plus).to_s+"]/text()")
        t2 = row_statistic.css("td["+(5-plus).to_s+"]/text()")
        t3 = row_statistic.css("td["+(7-plus).to_s+"]/text()")
        t1 = row_statistic.css("td["+(9-plus).to_s+"]/text()")
        reb = row_statistic.css("td["+(11-plus).to_s+"]/text()")
        a = row_statistic.css("td["+(12-plus).to_s+"]/text()")
        br = row_statistic.css("td["+(13-plus).to_s+"]/text()")
        bp = row_statistic.css("td["+(14-plus).to_s+"]/text()")
        c = row_statistic.css("td["+(15-plus).to_s+"]/text()")
        tap = row_statistic.css("td["+(16-plus).to_s+"]/text()")
        m = row_statistic.css("td["+(17-plus).to_s+"]/text()")
        fp = row_statistic.css("td["+(18-plus).to_s+"]/text()")
        fr = row_statistic.css("td["+(19-plus).to_s+"]/text()")
        mas_menos = row_statistic.css("td["+(20-plus).to_s+"]/text()")
        v = row_statistic.css("td["+(21-plus).to_s+"]/text()")
        sm = row_statistic.css("td["+(22-plus).to_s+"]/text()")

        values = {
          game: game.to_s,
          min: minutos.to_s,      pt: puntos.to_s,          t2: t2.to_s, 
          t3: t3.to_s,            t1: t1.to_s,              reb: reb.to_s,
          a: a.to_s,              br: br.to_s,              bp: bp.to_s,                
          c: c.to_s,              tap: tap.to_s,            m: m.to_s,
          fp: fp.to_s,            fr: fr.to_s,              mas_menos: mas_menos.to_s,
          v: v.to_s,              sm: sm.to_s
        }
        statistic.send("#{partido}=", values)
        statistic.played_games = statistic.played_games + 1 unless game.blank?
        statistic.save!
      end
    end
  end

  private
    def set_defaults
      values = {}
      FIELDS.zip(FIELDS_DEFAULT).each do |field, default|
        values[field] = default
      end
      (1..NUM_GAMES).each do |week|
        self.send("week_#{week}=", values)
      end
    end
end

app/controllers/api/v1/statistics_controller.rb
class Api::V1::StatisticsController < Api::V1::ApiController

  def index
    @statistics = Statistic.all.joins(:player).includes(:player)

    @statistics = @statistics.where(season: params[:season]) if params[:season].present?
    @statistics = @statistics.where("players.position = ? ", params[:position]) if params[:position].present?
    @statistics = @statistics.where("players.active = ? ", params[:active]) if params[:active].present?
    @players = @players.first(params[:limit]) if params[:limit].present?

    expose @statistics, include: [:player]
  end

  def trending_players
  	params[:season] = CURRENT_SEASON
    params[:round] = params[:round] || CURRENT_ROUND.to_i - 1

    @statistics = Statistic.all.joins(:player).includes(player: :team)

    @statistics = @statistics.where(season: params[:season]) if params[:season].present?
  	@statistics = @statistics.where("statistics.week_#{params[:round]} ->> '#{params[:order]}' != ''") if params[:order] and params[:round]
  	@statistics = @statistics.order("statistics.week_#{params[:round]} -> '#{params[:order]}' DESC") if params[:order] and params[:round]
  	@statistics = @statistics.first(params[:limit]) if params[:limit]

    expose @statistics, include: [player: :team]
  end	

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  load_and_authorize_resource
  require 'nokogiri'
  require 'open-uri'

  def index
    @statistics = Statistic.all
  end

  def new
    @statistic = Statistic.new
  end

  def create
    @statistic = Statistic.create(statistic_params)
    @statistics = Statistic.all
  end

  def edit
  end

  def update
    @statistic.update_attributes(statistic_params)
  end

  def destroy
    @statistic.destroy
  end

  def import
    Statistic.import_statistics
    redirect_to admin_statistics_path and return
  end

  private
    def find_statistic
      @statistic = Statistic.find(params[:id])
    end

    def statistic_params
      params.require(:statistic).permit([:season])
    end
end

app/views/statistics/_form.html.haml
.x_panel
  .x_title
    %h2= "Editar Estadística"
    .clearfix
  .x_content
    = form_for @statistic, url: @statistic.new_record? ? statistics_path : statistic_path(@statistic), remote: true, html: {class: "form-horizontal"} do |f|
      .form-group
        .col-md-3.control-label= f.label "Player"
        .col-md-5= @statistic.player
      .form-group
        .col-md-3.control-label= f.label "Position"
        .col-md-5= @statistic.player.position.text if @statistic.player.position
      .form-group
        .col-md-3.control-label= f.label "Team"
        .col-md-5= @statistic.player.team
      .form-group
        .col-md-3.control-label= f.label "Season"
        .col-md-5= f.text_field :season, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Statistics"
        .col-md-9
          = render partial: "statistics_player", locals: {statistic: @statistic}
          
      .form-group
        .col-md-3
        .col-md-5
          = f.submit "Save", class: "btn btn-primary"
          %button.btn.btn-default{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}= t("cancel")

app/views/statistics/_statistic.html.haml
%tr{:id => dom_id(statistic)}  
  %td= statistic.id
  %td= statistic.season
  %td= player_image statistic.player, "height_22"
  %td= link_to statistic.player.name, statistic.player
  %td= team_image statistic.player.team, "height_22"
  %td= statistic.player.position.text if statistic.player.position
  %td.actions
    %ul.nav.navbar-right.panel_toolbox.list-inline
      %li
        = link_to edit_statistic_path(statistic), remote: true do
          %i.fa.fa-pencil
      %li
        = link_to statistic_path(statistic), remote: true, method: :delete, data: {confirm: t(".confirm_delete"), disable_with: t(".deleting")} do
          %i.fa.fa-trash-o

app/views/statistics/_statistics_player.html.haml
.table-responsive
  %table.table.table-striped
    %thead
      %th
      - Statistic.fields.each do |field|
        %th= t("#{field}")
    
      %tbody
        - (1..CURRENT_ROUND.to_i-1).each do |week|
          %tr
            %td= week
            - week = statistic.send("week_"+week.to_s)
            - Statistic.fields.each do |field|
              %td= week[field]
        %tr
          %th{colspan: 2}= "Promedio"
          - Statistic.fields.each do |field|
            - unless field == "game"
              %th= statistic.promedio[field]
        %tr
          %th{colspan: 2}= "Total"
          - Statistic.fields.each do |field|
            - unless field == "game"
              %th= statistic.total[field]

app/views/statistics/create.js.erb
<%= modal j render partial: "statistics/form" %>

app/views/statistics/destroy.js.erb
$("#<%= dom_id @statistic %>").replaceWith("");

app/views/statistics/edit.js.erb
<%= modal j render partial: "statistics/form", locals: {statistic: @statistic} %>

app/views/statistics/index.html.haml
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t(".title")
        %ul.nav.navbar-right.panel_toolbo
          %li.dropdown
            %a{:href => "#", data: {toggle: "dropdown", role: "button", aria: {expanded: "false"}}}
              %i.fa.fa-wrench
            %ul.dropdown-menu.pull-right{:role => "menu"}
              %li= link_to t(".import_statistics"), import_statistics_path
              %li= link_to t(".create"), new_statistic_path, remote: true
        .clearfix
      .x_content
        %table#datatable.table.table-striped.table-bordered
          %thead
            %tr
              %th.col-md-1= "ID"
              %th.col-md-1= "Season"
              %th.col-md-1= ""
              %th.col-md-2= "Player"
              %th.col-md-1= "Team"
              %th.col-md-1= "Position"
              %th.col-md-1= "Options"
          %tbody
            = render @statistics
          

app/views/statistics/show.html.haml
.row
  .col-xs-12
    %h1= @statistic.name
    
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %tbody
          %tr
            %td.col-xs-2{rowspan: 5}
              = statistic_image @statistic
          %tr
            %th= "Position"
            %td= @statistic.position
          %tr
            %th= "Height"
            %td= @statistic.height
          %tr
            %th= "Date of Birth"
            %td= @statistic.date_of_birth.to_s(:short_date)
          %tr 
            %th= "Place of Birth"
            %td= @statistic.place_of_birth
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead.sortable
          %tr
            %th.col-xs-2= "Imatge"
            %th.col-xs-2= "Id"
            %th.col-xs-2= "Nom"
            %th.col-xs-2= "Position"
            %th.col-xs-2= "Price"
            %th.col-xs-2= "Team"
        %tbody=# render @statistic.statistics
  .col-xs-12
    %h1= "Acumulats 2015"
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead.sortable
          %tr
            %th.col-xs-2= "ID"
            %th.col-xs-2= "Jornada"
            %th.col-xs-2= "Equip"
            %th.col-xs-2= "Rival"
            %th.col-xs-2= "Acumulats Fets"
            %th.col-xs-2= "Acumulats Rebuts"
        %tbody=# render @statistic.statistics.statistic.where(season: "2015").order(:game_number)

app/views/statistics/update.js.erb
$("#<%= dom_id @statistic %>").replaceWith("<%= j render partial: "statistics/statistic", locals: {statistic: @statistic} %>");
$("#site-modal").modal("hide");