config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"

  # BACK-END
  resources :contents
  resources :teams
  resources :players do
    collection do 
      get :import
      get :import_numbers
      get :calculate_prices
    end
  end
  resources :games do
    collection do 
      get :import
      get :import_table
    end
  end
  resources :statistics do
    collection do 
      get :import
    end
  end
  resources :settings

  # API #
  namespace :api do
    namespace :v1 do 
      resources :contents
      resources :games do 
        collection do
          get :calendar
        end
      end
      resources :players
      resources :statistics do
        collection do
          get :trending_players
        end
      end
      resources :teams
    end
  end

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#
require 'nokogiri'
require 'open-uri'
require 'webrick/httputils'
require 'date'

class Game < ActiveRecord::Base
  # !**************************************************
  # !                Associations
  # !**************************************************
  belongs_to :local_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"

  # !**************************************************
  # !                Validations
  # !**************************************************

  # !**************************************************
  # !                Callbacks
  # !**************************************************

  # !**************************************************
  # !                  Other
  # !**************************************************  
  default_scope { order("games.round::integer ASC").order(game_date: :asc) }
  scope :by_season, -> (season) { where(:season => season) }
  scope :by_round,  -> (round)  { where(:round  => round) }

  def self.active
    where(active: true)
  end

  def to_param
    [id.to_s, local_team.name.parameterize, away_team.name.parameterize].join("-")
  end

  # !**************************************************
  # !                Imports
  # !**************************************************
  def self.import_games
    games_url = Setting.find_by_key("games_url").value
    games_html = Nokogiri::HTML(open(games_url.to_s))
    num_game = 0

    games_html.css("table.menuclubs > tr").each do |game_row|
      teams = game_row.css('td[2]//text()').to_s
      date_score = game_row.css('td[3]//text()').to_s
      array_teams = teams.split(" - ")
      local = Team.find_by_name(array_teams[0])
      away = Team.find_by_name(array_teams[1])

      if local and away 
        game = Game.where(local_team_id: local.id).where(away_team_id: away.id).first
        unless game
          game = Game.new
          game.local_team_id = local.id
          game.away_team_id = away.id
          
          unless date_score.include? ' - '
            game.game_date = !date_score.blank? ? DateTime.parse(date_score) : ""
          end
        end

        # Sate - Result
        if date_score.include? ' - '
          array_score = date_score.split(" - ")
          game.local_score = array_score[0]
          game.away_score = array_score[1]
        end

        game.season = CURRENT_SEASON
        game.round = (num_game / 8) + 1
        game.save!
      end
      num_game += 1
    end
  end

  def self.import_game game
    games_url = game.href
    games_url.force_encoding('binary')
    games_url = WEBrick::HTTPUtils.escape(games_url)
    game_html = Nokogiri::HTML(open(games_url))

    game_html.css("td.fichaJugadorData").each do |game_data|
      position_detail = game_data.css('p[2]//text()').to_s
      height = game_data.css('p[3]/strong[1]/text()').to_s
      date_of_birth = game_data.css('p[5]/strong[1]/text()').to_s
      place_of_birth = game_data.css('p[5]/strong[2]/text()').to_s
      
      position_detail = position_detail
      height = height
      date_of_birth = date_of_birth
      place_of_birth = place_of_birth
    end
    game_html.css("td.fichaJugadorimg").each do |game_image|
      image = Array.wrap(game_image.css("img").map { |link| link['src'] })[0].to_s
      image = image
    end
    save!
  end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::ApiController

  skip_authorization_check

  def index
  	params[:season] = CURRENT_SEASON
  	params[:round] = params[:round] || CURRENT_ROUND.to_i - 1

  	@games = Game.all
  	
  	@games = @games.where(:season => params[:season]) if params[:season]
    @games = @games.where(:round => params[:round]) if params[:round]

    expose @games  
  end

  def show
  	expose Game.where(id: params[:id]).includes(local_team: [players: :statistics], away_team: [players: :statistics]), include: [local_team: [players: :statistics], away_team: [players: :statistics]]
  end

  def calendar
    @games = Game.includes(:local_team, :away_team).by_season(CURRENT_SEASON).order(:round)
    expose @games, include: [:local_team, :away_team]
  end

  private

    def game_params
      params.require(:game).permit([:id, :name, :short_code, :season, :round, :active])
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  load_and_authorize_resource
  require 'nokogiri'
  require 'open-uri'
  require 'webrick/httputils'
  require 'date'

  def index
    @games = Game.active.order(:game_date)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    @games = Game.active.order(:game_date)
  end

  def edit
  end

  def update
    @game.update_attributes(game_params)
  end

  def destroy
    @game.destroy
  end

  def import
    Game.import_games
    redirect_to games_path and return
  end
  
  def import_table
    Team.import_table
    redirect_to games_path and return
  end

  private
    def find_game
      @game = Player.find(params[:id])
    end

    def game_params
      params.require(:game).permit([:season, :round, :local_team_id, :away_team_id, :game_date, :local_score, :away_score])
    end
end

app/views/games/_form.html.haml
.x_panel
  .x_title
    %h2= "Editar Partido"
    .clearfix
  .x_content
    = form_for @game, url: @game.new_record? ? games_path : game_path(@game), remote: true, html: {class: "form-horizontal"} do |f|
      .form-group
        .col-md-3.control-label= f.label "Season"
        .col-md-5= f.text_field :season, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Round"
        .col-md-5= f.text_field :round, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Local Team"
        .col-md-5= f.collection_select :local_team_id, Team.active, :id, :name, {}, {class: 'form-control select2'}
      .form-group
        .col-md-3.control-label= f.label "Away Team"
        .col-md-5= f.collection_select :away_team_id, Team.active, :id, :name, {}, {class: 'form-control select2'}
      .form-group
        .col-md-3.control-label= f.label "Date"
        .col-md-5= f.text_field :game_date, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Local Score"
        .col-md-5= f.text_field :local_score, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Away Score"
        .col-md-5= f.text_field :away_score, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Active"
        .col-md-5= f.check_box :active

      .form-group
        .col-md-3
        .col-md-5
          = f.submit "Save", class: "btn btn-primary"
          %button.btn.btn-default{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}= t("cancel")

app/views/games/_game.html.haml
%tr{:id => dom_id(game)}
  %td= game.id
  %td= game.season
  %td= game.round
  %td= link_to game.local_team.name, game.local_team
  %td= game.local_score
  %td= game.away_score
  %td= link_to game.away_team.name, game.away_team
  %td= short_date game.game_date
  %td.actions
    %ul.nav.navbar-right.panel_toolbox.list-inline
      %li
        = link_to edit_game_path(game), remote: true do
          %i.fa.fa-pencil
      %li
        = link_to game_path(game), remote: true, method: :delete, data: {confirm: t(".confirm_delete"), disable_with: t(".deleting")} do
          %i.fa.fa-trash-o

app/views/games/create.js.erb
<%= modal j render partial: "games/form" %>

app/views/games/destroy.js.erb
$("#<%= dom_id @game %>").replaceWith("");

app/views/games/edit.js.erb
<%= modal j render partial: "games/form", locals: {game: @game} %>

app/views/games/index.html.haml
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t(".title")
        %ul.nav.navbar-right.panel_toolbo
          %li.dropdown
            %a{:href => "#", data: {toggle: "dropdown", role: "button", aria: {expanded: "false"}}}
              %i.fa.fa-wrench
            %ul.dropdown-menu.pull-right{:role => "menu"}
              %li= link_to t(".import_games"), import_games_path
              %li= link_to t(".import_table"), import_table_games_path
              %li= link_to t(".create"), new_game_path, remote: true
        .clearfix
      .x_content
        %table#datatable.table.table-striped.table-bordered
          %thead
            %tr
              %th.col-md-1= "ID"
              %th.col-md-1= "Season"
              %th.col-md-1= "Round"
              %th.col-md-2= "Local"
              %th.col-md-1= ""
              %th.col-md-1= ""
              %th.col-md-2= "Visitant"
              %th.col-md-2= "Data"
              %th.col-md-1= "Options"
          %tbody
            = render @games
          

app/views/games/show.html.haml
.row
  .col-xs-12
    %h1= @game.name
    
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %tbody
          %tr
            %td.col-xs-2{rowspan: 5}
              = game_image @game
          %tr
            %th= "Position"
            %td= @game.position
          %tr
            %th= "Height"
            %td= @game.height
          %tr
            %th= "Date of Birth"
            %td= @game.date_of_birth.to_s(:short_date)
          %tr 
            %th= "Place of Birth"
            %td= @game.place_of_birth
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead.sortable
          %tr
            %th.col-xs-2= "Imatge"
            %th.col-xs-2= "Id"
            %th.col-xs-2= "Nom"
            %th.col-xs-2= "Position"
            %th.col-xs-2= "Price"
            %th.col-xs-2= "Team"
        %tbody=# render @game.games
  .col-xs-12
    %h1= "Acumulats 2015"
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead.sortable
          %tr
            %th.col-xs-2= "ID"
            %th.col-xs-2= "Jornada"
            %th.col-xs-2= "Equip"
            %th.col-xs-2= "Rival"
            %th.col-xs-2= "Acumulats Fets"
            %th.col-xs-2= "Acumulats Rebuts"
        %tbody=# render @game.statistics.game.where(season: "2015").order(:game_number)
  .col-xs-12
    %h1= "Acumulats 2014"
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead.sortable
          %tr
            %th.col-xs-2= "ID"
            %th.col-xs-2= "Jornada"
            %th.col-xs-2= "Equip"
            %th.col-xs-2= "Rival"
            %th.col-xs-2= "Acumulats Fets"
            %th.col-xs-2= "Acumulats Rebuts"
        %tbody=# render @game.statistics.game.where(season: "2014").order(:game_number)

app/views/games/update.js.erb
$("#<%= dom_id @game %>").replaceWith("<%= j render partial: "games/game", locals: {game: @game} %>");
$("#site-modal").modal("hide");