config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"

  # BACK-END
  resources :contents
  resources :teams
  resources :players do
    collection do 
      get :import
      get :import_numbers
      get :calculate_prices
    end
  end
  resources :games do
    collection do 
      get :import
      get :import_table
    end
  end
  resources :statistics do
    collection do 
      get :import
    end
  end
  resources :settings

  # API #
  namespace :api do
    namespace :v1 do 
      resources :contents
      resources :games do 
        collection do
          get :calendar
        end
      end
      resources :players
      resources :statistics do
        collection do
          get :trending_players
        end
      end
      resources :teams
    end
  end

end

app/views/inc/left_side_menu/_menu_footer_buttons.html.erb
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <%= link_to('<span class="glyphicon glyphicon-off" aria-hidden="true"></span>'.html_safe, destroy_user_session_path, :method => :delete, class: "logout", title: "Log Out", data: { toggle: 'tooltip', placement: 'top'}) %>
</div>

app/views/inc/left_side_menu/_menu_profile.html.erb
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="/images/img.jpg" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2><%= current_user %></h2>
  </div>
</div>

app/views/inc/left_side_menu/_options.html.erb
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
        <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="index.html">Dashboard</a></li>
            <li><a href="index2.html">Dashboard2</a></li>
            <li><a href="index3.html">Dashboard3</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-gamepad"></i> Data <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "Players", players_path %></li>
            <li><%= link_to "Statistics", statistics_path %></li>
            <li><%= link_to "Games", games_path %></li>
          </ul>
        </li>
        <li><a><i class="fa fa-file-text-o"></i> CMS <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><%= link_to "Content", contents_path %></li>
          </ul>
        </li>
        <li><a><i class="fa fa-cogs"></i> Settings <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><%= link_to "ENV Vars", settings_path %></li>
          </ul>
        </li>       
    </ul>
  </div>
</div>

app/views/inc/left_side_menu/_title.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="#" class="site_title"><i class="fa fa-dribbble"></i> <span>EstadisticasACB!</span></a>
</div>