config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"

  # BACK-END
  resources :contents
  resources :teams
  resources :players do
    collection do 
      get :import
      get :import_numbers
      get :calculate_prices
    end
  end
  resources :games do
    collection do 
      get :import
      get :import_table
    end
  end
  resources :statistics do
    collection do 
      get :import
    end
  end
  resources :settings

  # API #
  namespace :api do
    namespace :v1 do 
      resources :contents
      resources :games do 
        collection do
          get :calendar
        end
      end
      resources :players
      resources :statistics do
        collection do
          get :trending_players
        end
      end
      resources :teams
    end
  end

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#

class Player < ActiveRecord::Base
  # !**************************************************
  # !                Associations
  # !**************************************************
  belongs_to :team
  has_many :statistics

  # !**************************************************
  # !                Validations
  # !**************************************************

  # !**************************************************
  # !                Callbacks
  # !**************************************************
  before_update :set_position

  # !**************************************************
  # !                  Other
  # !**************************************************
  scope :order_by_position, -> { order(%q{
                          case players.position
                            when 'base' then 1
                            when 'alero' then 2
                            when 'pivot' then 3
                          end
                        })
                  .order(:name) 
                }  
  include PlayerAllowed
  extend Enumerize
  enumerize :position, in: ["base", "alero", "pivot"], predicates: true
  
  def to_s
    name
  end

  def self.search(q, options={})
    where("name ILIKE ?", "%#{q}%").order( "name")
  end

  def print_price
    ActiveSupport::NumberHelper.number_to_delimited(price.to_i, :delimiter => ".")
  end

  def set_position
    unless position_detail.nil?
      self.position_detail = position_detail.parameterize.underscore
      self.position = position_detail
      self.position = "pivot" if self.position_detail == "Alapívot".parameterize.underscore
      self.position = "alero" if self.position_detail == "Escolta".parameterize.underscore
    end
  end

  # Getting Data
  def stat_field field
    statistics.by_season([CURRENT_SEASON]).send(field).to_f
  end

  def promedio_stat field
    statistics.by_season([CURRENT_SEASON]).promedio[field].to_f
  end

  def total_stat field
    statistics.by_season([CURRENT_SEASON]).total[field].to_f
  end

  def played_games
    statistics.by_season([CURRENT_SEASON]).played_games.to_i
  end

  def promedio_minutos
    statistics.by_season([CURRENT_SEASON]).promedio["min"].to_s.chop.to_f
  end

  def total_minutos
    statistics.by_season([CURRENT_SEASON]).total["min"].to_s.chop.to_f
  end

  def por_40_minutos field
   (promedio_stat(field) / promedio_minutos * 40).round(2)
  end

  def current_price
    price[CURRENT_ROUND]
  end

  def sube_15
    (( (( (current_price.to_i * 1.15) / 70000)) * (stat_field("played_games") + 1)) - total_stat("sm").to_f).round(2)
  end

  def baja_15
    (( (( (current_price.to_i * 0.85) / 70000)) * (stat_field("played_games") + 1)) - total_stat("sm").to_f).round(2)
  end

  def se_mantiene
    (( (( (current_price.to_i) * 1.to_f / 70000)) * (stat_field("played_games") + 1)) - total_stat("sm").to_f).round(2)
  end
  # Getting Data

  def to_param
    [id.to_s, name.parameterize].join("-")
  end

  # !**************************************************
  # !                Imports
  # !**************************************************
  def self.import_players
    players_url = Setting.find_by_key("players_url").value
    players_html = Nokogiri::HTML(open(players_url))

    players_html.css("table.listaJugadores > tr").each do |player_row|
      name = player_row.css('td[1]//text()').to_s
      team_name = player_row.css('td[2]/text()').to_s

      unless name.blank?
        unless player = Player.find_by_name(name)
          player = Player.new
        end
        player.name = name
        player.team = Team.where("name = ? OR second_name = ?", team_name, team_name).first

        player.href = Array.wrap(player_row.css("td[1]/a").map { |link| link['href'] })[0].to_s
        if player.valid?
          player.save!

          import_player player
        end
      end
    end
  end

  def self.import_player player
    players_url = player.href
    players_url.force_encoding('binary')
    players_url = WEBrick::HTTPUtils.escape(players_url)
    player_html = Nokogiri::HTML(open(players_url))

    player_html.css("td.fichaJugadorData").each do |player_data|
      position_detail = player_data.css('p[2]//text()').to_s
      height = player_data.css('p[3]/strong[1]/text()').to_s
      date_of_birth = player_data.css('p[5]/strong[1]/text()').to_s
      place_of_birth = player_data.css('p[5]/strong[2]/text()').to_s

      player.position_detail = position_detail
      player.height = height
      player.date_of_birth = date_of_birth
      player.place_of_birth = place_of_birth
    end
    player_html.css("td.fichaJugadorimg").each do |player_image|
      image = Array.wrap(player_image.css("img").map { |link| link['src'] })[0].to_s
      if image
        a_image = image.split('/')
        unless a_image.last.nil?
          a_image.last.gsub! '.jpg', '.png'
          player.image = a_image.last
        end
      end
    end
    player_html.css("table.fichaJugadorSM").each do |player_sm|
      price = player_sm.css('tr[3]/td[2]/text()')
      player.price["#{CURRENT_ROUND}"] = "#{price}".delete!('.').to_i
    end
    player.save!
  end

  def self.calculate_prices
    players_url = "http://www.rincondelmanager.com/smgr/stats.php?nombre="
    not_found_players = []
    current_round = Setting.find_by_key("current_round").value.to_i
    session_rounds = Setting.find_by_key("session_rounds").value.to_i

    Player.all.each do |player|
      row = 1
      escape_rows = 4
      player_url = WEBrick::HTTPUtils.escape(players_url + player.name)
      puts player_url
      if player_html = Nokogiri::HTML(open(player_url))
        prices = {}
        player_html.css("table.states-table > tbody > tr").each do |game_row|
          price_up_down = game_row.css("td[13] > text()").first.to_s.delete!('.').to_i
          round = game_row.css("td[1] > text()").to_s.to_i
          if row <= current_round  
            if (1..current_round).include?(round)
              prices[round] = price_up_down
              row = row + 1
            end
          end        
        end

        (current_round).downto(1) do |i|
          if player.price[i.to_s] and prices[i-1]
            if player.team.rest_round_1 == current_round.to_s or player.team.rest_round_2 == current_round.to_s
              player.price[(i - 1).to_s] = player.price[i.to_s]
            else
              player.price[(i - 1).to_s] = (player.price[i.to_s] + prices[i-1] * -1.to_i) 
            end
          else
            player.price[(i - 1).to_s] = 0
          end
        end
        player.save!
      else
        not_found_players << player
      end
    end
    puts "Not Found Players = "+not_found_players.count.to_s
    not_found_players.each do |p|
      puts p.name
    end
  end

  def self.import_numbers
    Team.all.each do |team|
      team_url = "http://www.acb.com/plantilla.php?cod_equipo=#{team.acb_short_code}&cod_competicion=LACB&cod_edicion=61"
      team_html = Nokogiri::HTML(open(team_url))
      team_html.css("table.plantilla tr").each do |player_data|
        number = player_data.css('td[1]/text()').to_s
        name = player_data.css('td[2]/a/text()').to_s
        if player = Player.find_by_name(name)
          player.number = number
          player.save!
        end
      end
    end
  end

end

app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < Api::V1::ApiController

  skip_authorization_check

  def index
    @players = Player.all
    
    @players = @players.where(position: params[:position]) if params[:position].present?
    @players = @players.where(active: params[:active]) if params[:active].present?
    @players = @players.where("lower(players.name) ILIKE ?", "%#{params[:name].downcase}%") if params[:name].present?
    @players = @players.first(params[:count]) if params[:count].present?

    expose @players
  end

  def show
  	expose Player.where(id: params[:id]).includes(:team, :statistics), include: [:team, :statistics]
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  include ActionView::Helpers::NumberHelper
  load_and_authorize_resource
  require 'nokogiri'
  require 'open-uri'
  require 'webrick/httputils'

  def index
    @players = Player.active
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)
    @players = Player.active
  end

  def edit
  end

  def update
    @player.update_attributes(player_params)
  end

  def destroy
    @player.destroy
  end

  def calculate_prices
    Player.calculate_prices
    redirect_to admin_players_path and return
  end

  def import
    Player.import_players
    redirect_to admin_players_path and return
  end

  def import_numbers
    Player.import_numbers

    redirect_to admin_players_path and return
  end

  private
    def find_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit([:name, :position, :team_id, :href, :active, :best_round_val, :best_round_points, :best_round_rebounds, :best_round_assists, :best_round_3points])
    end
end

app/helpers/players_helper.rb
module PlayersHelper

  def player_image player, folder = "original"
    if player.image
      logical_path = 'players/'+folder+'/'+player.image.to_s
      if asset_available? logical_path
        image_tag(asset_path(logical_path), alt: player.full_name).html_safe if player.image
      else
        image_tag(asset_path('players/'+folder+'/default.jpg'), alt: player.full_name).html_safe
      end
    else 
      image_tag(asset_path('players/'+folder+'/default.jpg'), alt: player.full_name).html_safe
    end
  end

  def player_price price
    number_with_delimiter(price, delimiter: ".")
  end
end

app/views/players/_form.html.haml
.x_panel
  .x_title
    %h2= "Editar Jugador"
    .clearfix
  .x_content
    = form_for @player, url: @player.new_record? ? players_path : player_path(@player), remote: true, html: {class: "form-horizontal"} do |f|
      .form-group
        .col-md-3.control-label= f.label "Name"
        .col-md-5= f.text_field :name, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "Position"
        .col-md-5= f.select :position, Player.position.options, {}, {class: 'form-control select2'}
      .form-group
        .col-md-3.control-label= f.label "Team"
        .col-md-5= f.collection_select :team_id, Team.active, :id, :name, {}, {class: 'form-control select2'}
      .form-group
        .col-md-3.control-label= f.label "URL"
        .col-md-5= f.text_field :href, class: 'string form-control'
      .form-group
        .col-md-3.control-label= f.label "MPV Round"
        .col-md-5= f.check_box :best_round_val
      .form-group
        .col-md-3.control-label= f.label "Top Points Round"
        .col-md-5= f.check_box :best_round_points
      .form-group
        .col-md-3.control-label= f.label "Top Rebounds Round"
        .col-md-5= f.check_box :best_round_rebounds
      .form-group
        .col-md-3.control-label= f.label "Top Assists Round"
        .col-md-5= f.check_box :best_round_assists
      .form-group
        .col-md-3.control-label= f.label "Top 3 Points Round"
        .col-md-5= f.check_box :best_round_3points
      .form-group
        .col-md-3.control-label= f.label "Active"
        .col-md-5= f.check_box :active
      .form-group
        .col-md-3
        .col-md-5
          = f.submit "Save", class: "btn btn-primary"
          %button.btn.btn-default{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}= t("cancel")

app/views/players/_player.html.haml
%tr{:id => dom_id(player)} 
  %td= player.id
  %td= player_image player, "height_22"
  %td= player.number
  %td= link_to player.name, player_path(player)
  %td= link_to player.team.name, team_path(player.team) if player.team
  %td= player_price player.price[CURRENT_ROUND]
  %td= player.position.try(:text) if player.position
  %td
    - if player.active
      %i.glyphicon.glyphicon-ok
    - else
      %i.glyphicon.glyphicon-remove
  %td.actions
    %ul.nav.navbar-right.panel_toolbox.list-inline
      %li
        = link_to edit_player_path(player), remote: true do
          %i.fa.fa-pencil
      %li
        = link_to player_path(player), remote: true, method: :delete, data: {confirm: t(".confirm_delete"), disable_with: t(".deleting")} do
          %i.fa.fa-trash-o

app/views/players/create.js.erb
<%= modal j render partial: "players/form" %>

app/views/players/destroy.js.erb
$("#<%= dom_id @player %>").replaceWith("");

app/views/players/edit.js.erb
<%= modal j render partial: "players/form", locals: {player: @player} %>

app/views/players/index.html.haml
.row
  .col-md-12.col-sm-12.col-xs-12
    .x_panel
      .x_title
        %h2= t(".title")
        %ul.nav.navbar-right.panel_toolbo
          %li.dropdown
            %a{:href => "#", data: {toggle: "dropdown", role: "button", aria: {expanded: "false"}}}
              %i.fa.fa-wrench
            %ul.dropdown-menu.pull-right{:role => "menu"}
              %li= link_to t(".import_players"), import_players_path
              %li= link_to t(".calculate_prices"), calculate_prices_players_path
              %li= link_to t(".import_numbers"), import_numbers_players_path
              %li= link_to t(".create"), new_player_path, remote: true
        .clearfix
      .x_content
        %table#datatable.table.table-striped.table-bordered
          %thead
            %tr
              %th.col-md-1= "ID"
              %th.col-md-1= ""
              %th.col-md-1= "#"
              %th.col-md-2= "Name"
              %th.col-md-2= "Team"
              %th.col-md-1= "Price"
              %th.col-md-2= "Position"
              %th.col-md-2= "Active"
              %th.col-md-1= "Options"
          %tbody
            = render @players
          

app/views/players/show.html.haml
.row
  .col-xs-12
    %h1= @player.name
    
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %tbody
          %tr
            %td.player_detail.col-xs-2{rowspan: 6}
              = player_image @player, "height_22"
          %tr
            %th= "Position"
            %td= @player.position.text if @player.position
          %tr
            %th= "Height"
            %td= @player.height
          %tr
            %th= "Date of Birth"
            %td= @player.date_of_birth.to_s(:short_date) if @player.date_of_birth
          %tr 
            %th= "Place of Birth"
            %td= @player.place_of_birth 
          %tr 
            %th= "Price"
            %td= player_price @player.price[CURRENT_ROUND]
  .col-xs-12
    = render partial: "statistics/statistics_player", locals: {statistic: @player.statistics.last}

app/views/players/update.js.erb
$("#<%= dom_id @player %>").replaceWith("<%= j render partial: "players/player", locals: {player: @player} %>");
$("#site-modal").modal("hide");